### PR TITLE
Transition JS to Snooze

### PR DESCRIPTION
**Pull request by joshuagruenstein**
Snooze is an excellent library for handling the view layer of API-centric webapps.  Halite's leaderboards and user display could benefit by using Snooze.
- [x] Main Leaderboard
- [ ] User information and tables

Note that transitioning all of Halite to Snooze would be impractical.  Rather, the ideal solution would be to use Snooze as a tool where it is needed: most notably, in rendering of leaderboards and user data.

### CODE REVIEW

**Comment by truell20** [comment]
Snooze isn't used by anyone right now and has 0% coverage.

**Comment by truell20** [comment]
We prefer to stick to popular, well-tested libraries, so that we know that we can depend on them others can easily understand our codebase. @Sydriax thoughts?

**Comment by joshuagruenstein** [comment]
Personally, I would consider Snooze to be more maintainable than your current JS codebase (although I may be a little biased).  Snooze is highly intuitive for beginners, and for basic usage is identical to popular template libraries such as Handlebars.js.  For more complex behaviors Snooze have comprehensive documentation and tutorials, and the codebase is only 400 lines: barely larger than Halite's current homebrew JS.

**Comment by truell20** [comment]
I wouldn't consider it more maintainable than modularized JS that does DOM manipulation with JQuery and most definitely not as well known.

**Comment by joshuagruenstein** [comment]
Then we have a difference of opinion.  Consider the difficulty of modifying the rendering.  For example, imagine if you wanted to add an inline style to leaderboard rows, or a link.  Your awkward system of HTML strings and escaped quotes is a high risk area, and significantly harder to maintain and iterate upon than Snooze templating.

**Comment by truell20** [comment]
Then small refactorings can be made to our current system. We can move away from the few instances where we use long inline HTML strings. There is no need for snooze.

**Comment by joshuagruenstein** [comment]
In the few instances where you use long inline HTML strings, Snooze is the perfect solution.  I'm not advocating overhauling the entire Halite frontend.  Rather, using it as a tool in the few instances in which it's practical.

**Comment by truell20** [comment]
Snooze is not the perfect solution for the reasons I have listed above. No one uses it, no one knows how to use it, and it is untested. Instead, refactoring is the solution. Besides, We are under a deadline. We don't have the time to start maintaining another library.

**Comment by joshuagruenstein** [comment]
You don't have to maintain it until it breaks, an unlikely occurrence due to its minimalism and simplicity.  In addition, I'm willing to offer a "lifetime warrantee" on Snooze: not only will I fix any bugs and add any improvements, but I will write a complete test suite with 100% coverage.

**Comment by truell20** [comment]
You use gotos.

**Comment by joshuagruenstein** [comment]
A) I am happy to refractor Snooze's DOM diffing and remove gotos.
B) If this PR remains closed, I will be very sad. 😢

**Comment by truell20** [comment]
Snooze is pretty nice. Would like to see how a post to reddit or hackernews would go before further consideration.

**Comment by joshuagruenstein** [comment]
😄

**Pull request closed without merging**
