### PR TITLE
Added C# starter pack

### PR DESCRIPTION
**Pull request by arseniybanayev**
You can use csc.exe to compile submitted C# bot source code to an executable bot exe (https://msdn.microsoft.com/en-us/library/78f4aasd.aspx). When that is set up, we can add a runGame.bat and runGame.sh

### CODE REVIEW

**Comment by truell20** [comment]
Can we use [mono gmcs](http://www.mono-project.com/docs/about-mono/languages/csharp/) instead?

**Comment by arseniybanayev** [comment]
Yeah, that would work, too. Do you need any help setting that up?

**Comment by truell20** [comment]
Getting these build errors when compiling HaliteHelper.cs with mono gmcs:

```HaliteHelper.cs(24,54): error CS1056: Unexpected character `$'
HaliteHelper.cs(28,29): error CS1056: Unexpected character `$'
HaliteHelper.cs(38,62): error CS1525: Unexpected symbol `=>', expecting `;', `{', or `where'
HaliteHelper.cs(83,55): error CS1056: Unexpected character `$'
HaliteHelper.cs(119,56): error CS1056: Unexpected character `$'
HaliteHelper.cs(121,56): error CS1056: Unexpected character `$'
HaliteHelper.cs(129,44): error CS1525: Unexpected symbol `=>', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(129,75): error CS1525: Unexpected symbol `;', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(143,33): error CS1525: Unexpected symbol `_sites', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(146,44): error CS1525: Unexpected symbol `;', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(149,33): error CS1525: Unexpected symbol `=', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(169,49): error CS1014: A get or set accessor expected
HaliteHelper.cs(169,53): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
HaliteHelper.cs(169,92): error CS1519: Unexpected symbol `)' in class, struct, or interface member declaration
HaliteHelper.cs(170,31): error CS1519: Unexpected symbol `!=' in class, struct, or interface member declaration
HaliteHelper.cs(170,45): error CS1519: Unexpected symbol `.' in class, struct, or interface member declaration
HaliteHelper.cs(170,60): error CS1525: Unexpected symbol `0', expecting `,' or `]'
HaliteHelper.cs(170,46): error CS1520: Class, struct, or interface method must have a return type
HaliteHelper.cs(170,75): error CS1525: Unexpected symbol `||', expecting `,' or `]'
HaliteHelper.cs(172,18): error CS1519: Unexpected symbol `return' in class, struct, or interface member declaration
HaliteHelper.cs(172,32): error CS1519: Unexpected symbol `(' in class, struct, or interface member declaration
HaliteHelper.cs(172,38): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
HaliteHelper.cs(172,46): error CS1519: Unexpected symbol `)' in class, struct, or interface member declaration
HaliteHelper.cs(175,23): error CS1525: Unexpected symbol `Map', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
HaliteHelper.cs(176,12): error CS1525: Unexpected symbol `var', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
HaliteHelper.cs(177,25): error CS1514: Unexpected symbol `new', expecting `.' or `{'
HaliteHelper.cs(177,23): error CS1530: Keyword `new' is not allowed on namespace elements
HaliteHelper.cs(177,26): error CS1525: Unexpected symbol `Map', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
```

**Comment by arseniybanayev** [comment]
Are you using a version that supports "string interpolation" from C# 6.0? The $ symbols where they appear in that file would cause compilation errors when targeting any earlier version.

**Comment by truell20** [comment]
As of March 2015, not supported in the released mcs build:

http://stackoverflow.com/questions/29208869/c-sharp-6-0-string-interpolation-in-mono-mcs

**Comment by arseniybanayev** [comment]
Well, that's annoying! I don't remember if csc.exe (Microsoft's official compiler) is available for free when downloading the .NET framework.

Alternatively, those lines can just be rewritten (e.g., $"hello {someVariable}" is just ("hello " + someVariable)), but then participants who use string interpolation in their bot code might be surprised that it fails to compile this but not other C# 6.0 features. Up to you...

**Comment by truell20** [comment]
Is csc.exe available on Linux?

**Comment by arseniybanayev** [comment]
Probably not natively, and I can't find anything online that indicates an alternative to mcs. I have to head out for now, but let's try just excluding string interpolation from the starter pack. I doubt that strings will appear at all in a good bot, anyway, and we can figure it out later if it becomes a big problem for a lot of users.

**Comment by arseniybanayev** [comment]
Try again, replaced string inteprolation with calls to string.Format

**Comment by truell20** [comment]
Sorry for the wait. Still having build issues.

```
HaliteHelper.cs(38,62): error CS1525: Unexpected symbol `=>', expecting `;', `{', or `where'
HaliteHelper.cs(129,44): error CS1525: Unexpected symbol `=>', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(129,75): error CS1525: Unexpected symbol `;', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(143,33): error CS1525: Unexpected symbol `_sites', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(146,44): error CS1525: Unexpected symbol `;', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(149,33): error CS1525: Unexpected symbol `=', expecting `{'
HaliteHelper.cs(129,25): error CS1551: Indexers must have at least one parameter
HaliteHelper.cs(169,49): error CS1014: A get or set accessor expected
HaliteHelper.cs(169,53): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
HaliteHelper.cs(169,92): error CS1519: Unexpected symbol `)' in class, struct, or interface member declaration
HaliteHelper.cs(170,31): error CS1519: Unexpected symbol `!=' in class, struct, or interface member declaration
HaliteHelper.cs(170,45): error CS1519: Unexpected symbol `.' in class, struct, or interface member declaration
HaliteHelper.cs(170,60): error CS1525: Unexpected symbol `0', expecting `,' or `]'
HaliteHelper.cs(170,46): error CS1520: Class, struct, or interface method must have a return type
HaliteHelper.cs(170,75): error CS1525: Unexpected symbol `||', expecting `,' or `]'
HaliteHelper.cs(172,18): error CS1519: Unexpected symbol `return' in class, struct, or interface member declaration
HaliteHelper.cs(172,32): error CS1519: Unexpected symbol `(' in class, struct, or interface member declaration
HaliteHelper.cs(172,38): error CS1519: Unexpected symbol `,' in class, struct, or interface member declaration
HaliteHelper.cs(172,46): error CS1519: Unexpected symbol `)' in class, struct, or interface member declaration
HaliteHelper.cs(175,23): error CS1525: Unexpected symbol `Map', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
HaliteHelper.cs(176,12): error CS1525: Unexpected symbol `var', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
HaliteHelper.cs(177,25): error CS1514: Unexpected symbol `new', expecting `.' or `{'
HaliteHelper.cs(177,23): error CS1530: Keyword `new' is not allowed on namespace elements
HaliteHelper.cs(177,26): error CS1525: Unexpected symbol `Map', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
```

**Comment by arseniybanayev** [comment]
Expression body syntax must not supported by this compiler, either. If the string interpolation syntax is the only thing from C# 6.0 not supported in the 6.0 compiler, then maybe you're using one for an earlier version?

**Comment by truell20** [comment]
Was running mcs 3 instead of mcs 4. Thank you so much for submitting this. We can take it from here.

**Comment by arseniybanayev** [comment]
Great! I'll submit my C# bot when you give the green light

**Comment by truell20** [comment]
@arseniybanayev You should be good to submit now

**Pull request merged**
