### PR TITLE
Finding matches now uses mu instead of rank

### PR DESCRIPTION
**Pull request by bovard**
As suggested here: http://forums.halite.io/t/faster-ranking-in-matchmaking/466

Open Questions:
1. there is no guarantee that anyone will have a mu "near enough" to us to match against, what should we do about this?
2. Do we always want to use sigma? or do we just want to use it for the first x games? or until our sigma is low?
3. should we change the query to look for other bots with a low sigma?

### CODE REVIEW

**Comment by Janzert** [comment]
`ABS(mu-{$seedPlayer['mu']}) < (5 / pow(rand(), 0.65))` as Daniel indirectly mentioned in his post this doesn't work because the difference in mu between player's isn't consistently 1 like it is for rankings.

The intial way I would approach it is to change the order by clause to be the absolute difference in mu plus a random factor.

**Comment by Janzert** [comment]
As an aside you're not (and shouldn't be) using sigma. Sigma is the uncertainty in the measured skill, while mu is the measure of skill.

**Comment by DanielVF** [comment]
Janzert is saying that the title of this PR is incorrect - this new style is using Mu, not Sigma.

**Comment by DanielVF** [comment]
I'd would indeed check that the opponents sigma is below some value. 

As a wild guess, I'd say below 1.2. Bots get there pretty fast (say 20-30 games, and in their first burst of play), while still keep newly submitted bots from being your opponents.

**Comment by DanielVF** [comment]
Yes, you do need to do something about there possibly not being opponents near you in Mu. And you don't just want to fight the nearest people in Mu to you, since as your ranks stabilize, that would make a for a lot of boring games.

I think I'd add another mu_rank field to the user table, pick games off that using the current system. You'd just need to smarten up the rank recalculation so that it computes both the current `rank` and the `mu_rank` and then stores them both. Should be pretty straightforward.

https://github.com/bovard/Halite/blob/b04ee6f30025238072f8009cede16f60693bd7bc/website/api/manager/ManagerAPI.php#L251

**Comment by Janzert** [comment]
Since the rank is updated after every game and the mu rank would only be used to pair games, on average the mu rank would only be used once before being updated. It seems rather wasteful to update every user record each time.

**Comment by bovard** [comment]
Don't want to cause a large rework here, think I have a workaround. If you have played less than 10 games, pretend your rank is half of what it actually is. This would allow the bot to climb much faster for the first few games as it will be facing higher level opponents.

I initially had this number at 25, but if you had a bot that loses every game, that doesn't make sense.

**Comment by bovard** [comment]
Ideally you could fine tune this to keep halving the rank until you lose a couple games, but I don't think that's info is on the player object.

**Comment by Janzert** [comment]
Completely untested but something like the following should do exactly what the current query does except using mu instead of rank. Adding sigma considerations into it can probably be put off until later.

`$players = $this->selectMultiple("SELECT * FROM User WHERE userID = (SELECT userID FROM User WHERE isRunning=1 and userID <> {$seedPlayer['userID']} ORDER BY ABS(mu-{$seedPlayer['rank']}) LIMIT (5 / pow(rand(), 0.65)) ORDER BY rand() LIMIT ".($numPlayers-1));`

**Comment by DanielVF** [comment]
We don't want to force players to face much harder bots for the first ten games. If you are new, you should stay fighting newer bots, not ones that clobber you every round. Makes you feel happier, and see how you can improve. This could turn away new player.

The goal is to get you to fighting the bots *of your level* faster, regardless of where your level is.

**Comment by bovard** [comment]
good call, guess that won't work unless we knew the w/l record

**Comment by DanielVF** [comment]
As long as that compiles and works, what you have now should be better than the current system.

I still think the Sigma restriction might be helpful, but this gets us 80% of the way there.

**Comment by DanielVF** [comment]
( Dang, every person in this thread did PlanetWars. )

**Comment by erdman** [comment]
Re matchmaking, people should be aware of how the Ants AIChallenge addressed it, which is documented here:  https://github.com/aichallenge/aichallenge/wiki/TrueSkill-Matchmaking

I think there are a number of ideas there that could improve our Halite matchmaking.  In particular, I want to point out that giving preference to players with low sigma for inclusion in matches will cause an imbalance in the allocation of matches, with players with a lot of match history (ie low sigma) being awarded even more matches.

**Comment by Janzert** [comment]
The actual (sql<sup>1</sup>) code to make the pairing from ants can be found at https://github.com/aichallenge/aichallenge/blob/epsilon/sql/2_generate_matchup.sql

And while I don't recall anything major changing after the description posted above was written there were 30 some commits to the code after that was last edited. The one thing I do recall we fought against for quite a while were low sigma players getting too many games to the exclusion of others.

<sup>1</sup> I wouldn't recommend doing it all in sql to anyone ;)

**Comment by DanielVF** [comment]
@erdman The idea is to set the Sigma threshold high enough that 95+% percent of bots are inside it, and only use this Sigma threshold on the High Sigma seeding.

All we really want to do is exclude newly submitted bots from being used to attempted to rank other newly submitted bots. I want to avoid this because because by default newly submitted bots will have the same Mu - thus a Mu only selection is very likely to match new bot with new bot. Also a high sigma vs high sigma match doesn't give TrueSkill much information to make adjustments from.

So this should take away very little play from newer bots (and 95% of their play is coming from their own High Sigma matches anyway which will be unaffected) and give only a tiny bit more to low sigma ones.

**Comment by erdman** [comment]
@DanielVF, sounds good, makes sense.  

@Janzert wrote a nice one-liner, but in trying to understand it, I'm realizing that @djma and @erdman are going to have a difficult time getting matches, because of the (current) 4 point gap between ranks #2 and #3.  The next four point spread is between #3 and ~#30.  So unless either of us is selected as the seed, the one-liner will sort us down to the bottom and we're unlikely to ever get a match.

**Comment by Janzert** [comment]
Even now the top (and bottom) of the rankings have roughly half the chance of getting chosen for a game as someone in the middle of the rankings. The offsetting force is you therefore get chosen as seed more frequently. Certainly there is a limit to how much choosing the seed from least recently used players can offset, currently it seems to be keeping up though.

**Comment by DanielVF** [comment]
@erdman The last one liner from @Janzert uses a subquery to order the bots by mu difference and choose a randomly sized spread of bots evenly on either side of the mu. Then the main query chooses a random selection from inside that even spread.

This takes care of the "mu gap" problem, and removes the penalty for that.

**Comment by Janzert** [comment]
@erdman is correct that by using absolute mu difference instead of absolute rank difference they will be chosen less frequently for other games. As I said above though this quite possibly will be compensated by being the seed more frequently. Using a mu ranking would also eliminate it. I'm reluctant to change to mu ranking without first showing that mu difference causes actual problems for two reasons. First that it will be a more complicated and slower query to run. Second that using mu difference will give better trueskill match quality than mu ranking.

**Comment by truell20** [comment]
Had to make some changes to the sql query to get it to work on our server (MySQL 5.7.11):

`"SELECT * FROM (SELECT userID FROM User WHERE isRunning=1 and userID <> {$seedPlayer['userID']} ORDER BY ABS(mu-{$seedPlayer['mu']}) LIMIT $muRankLimit) muRankTable ORDER BY rand() LIMIT".($numPlayers-1)`

MySQL doesn't seem to like computing the limit, so I think it needs to be computed in PHP.

**Comment by DanielVF** [comment]
So are you waiting for @bovard to add the working sql?

**Comment by truell20** [comment]
Yes.

**Comment by DanielVF** [comment]
Paging @bovard then. :D

**Comment by Janzert** [comment]
Just so it's easy for @bovard to paste in, the complete text that should replace line 97 is I believe the following:

            $muRankLimit = intval(5.0 / pow((float)mt_rand(1, mt_getrandmax())/(float)mt_getrandmax()), 0.65));
            $players = $this->selectMultiple("SELECT * FROM (SELECT userID FROM User WHERE isRunning=1 and userID <> {$seedPlayer['userID']} ORDER BY ABS(mu-{$seedPlayer['mu']}) LIMIT $muRankLimit) muRankTable ORDER BY rand() LIMIT ".($numPlayers-1));

This actually fixes a latent bug in both the original query and the previous query where if rand() returned 0.0 it would cause division by 0.

**Comment by erdman** [comment]
@Janzert, the issue I've highlighted stems from the fact that the mu scores are not uniformly distributed ... if they were, I think your code works as intended.  Since we know that mu's are normally distributed, we can normalize them first and then transform to a uniform distribution via the Normal CDF:
`norm.cdf((mu - 25) / 8.33)        #python-ish, I don't know php nor sql`

If we transform both seed player's and prospective player's mu's in this way and then order by absolute differences of the transforms, I think the issue goes away.  I don't speak either php or sql, so I can't code it.  If you don't have ready access to the normal distribution CDF in these languages, say the word, and I'll find an approximation formula.

**Comment by truell20** [comment]
@erdman @Janzert Is the sql not listed effectively using mu ranking, not mu difference (since we are merely ordering by the absolute mu difference not directly selecting based on it)? Wouldn't @djma and @erdman get about the same number of games as in the current system? Why is there a need to normalize?

**Comment by DanielVF** [comment]
@erdman I'm still not understanding what you are saying. We are proposing ordering all the mu's in order, then selecting after that. This means that Mu gaps don't matter, and distances are the same shape as the current rank-by-score.

**Comment by erdman** [comment]
The code as listed orders by the differential in mu between a prospective player and the seed player.  Problem is, the spread in mu is increasing as the mu is farther away from the mean (25).  This means there is a selection bias in favor of players closer to the mean (because they have smaller differentials to the seed player's mu) and against players farther from the mean.  The effect is probably negligible in most cases, but at the tail ends of the distribution, the effect is quite dramatic, such that the top 2-3 players are never going to get a match unless/until they are chosen as seed.  The solution I've proposed fixes this bug (I believe) by making the distribution of distances between mu's uniform, such that Janzert's code will choose players without bias.

**Comment by truell20** [comment]
I see. in the case of @djma and @erdman, if @Daniel-Wang were chosen as a seed, the players below him would crowd out @djma and @erdman.

**Comment by Janzert** [comment]
What @erdman is pointing is truly there, I'm just saying that it's probably not a problem. ;)

So in the current system we order everyone by distance in rank from the seed's rank. Two examples:
Seed is rank 300 so the order choices goes like this 301, 299, 298, 302, 297, 303... Where each pair is of equal distance and arbitrarily ordered.
Seed is rank 4 and choices go like this 3, 5, 2, 6, 7, 1, 8, 9, 10... Only the first three pairs are of equal distance then the rankings run out going up.

This actually means that middle ranks get chosen twice as frequently as end ranks since they can be chosen by both seeds that rank above and below them. This gets compensated by the least recently played seeding system. The couple of spot checks I did last night appeared that top seeds were in fact getting seeded roughly twice as frequently as a middle seed.

Now in the new system we are ordering by difference in mu from the seed. Since the mu's are not evenly distributed particularly at the ends the end pairing looks more like this:
Seed is rank 4 and the ordered pairing goes like this in ranks 5, 6, 7, 3, 8, ... 30, 2, 31, ... 34, 1, ...

So the very end ranks will be chosen even less than they currently are.

**Comment by Janzert** [comment]
Regarding using cdf, I'm not sure I trust that in practice mu's are actually normally distributed, admittedly probably close enough to not be a problem. Perhaps more importantly MySQL does not implement a cdf function so it would have to actually be defined manually. :(

**Comment by Janzert** [comment]
@truell20 I just noticed that the modified query you posted above seems to only return the userID for the selected players. Is that all that is required or should the subquery be a SELECT *?

**Comment by truell20** [comment]
The latter.

**Comment by erdman** [comment]
@Janzert, the best approximation to the normal CDF seems to be the logistic approximation:

F(z) = 1 / (1 + exp(-0.07056 * z**3 – 1.5976 * z)),
 where z = (mu - 25) / 8.33

Indirect source: Update #1 at http://www.johndcook.com/blog/2010/04/29/simple-approximation-to-normal-distribution/ 
Direct source: p. 10 of http://www.jiem.org/index.php/jiem/article/download/60/27

While I trust you are correct that the top players are serving as seed more often, I'd also wager that they are getting the fewest games, even now (my spot checks confirm!).  This seems worth fixing.

**Comment by Janzert** [comment]
So here's my latest sample of games at top and middle ranks played in the 12 hours from 10am to 10pm today.

Rank | Name | Total | Today
-----|-------|-------|------
1 | djma | 1817 | 27
2 | erdman | 203 | 31
3 | Gullesnuffe | 150 | 40
4 | Daniel-Wang | 131 | 33
5 | Maximophone | 141 | 52
6 | david-wu | 252 | 38
7 | markstev | 217 | 27
8 | adereth | 942 | 35
9 | daniel-shields | 554 | 42
10 | HalfVoxel | 166 | 37
 | | | 
341 | drkraftdinner | 48 | All in previous 5h33m
342 | MEL27 | 951 | 47
343 | CSBaum | 230 | 32
344 | Geoboardman | 656 | 37
345 | mastane | 836 | 39
346 | DanielWeitzenfeld | 410 | 39
347 | FlyingGraysons | 1862 | 44
348 | berak | 831 | 34
349 | mmhanif | 1008 | 43
350 | shubhamjain0594 | 347 | 34

Excluding the one player that had a fresh submission the average and standard deviation for the two groups is, Top10 avg 36.2 stdev 7.5, Middle 38.8 stdev 5.1.

So from what I can see there is no significant difference currently.

**Comment by Janzert** [comment]
So I started to look into what the effect of approximately transforming to a normal distribution would have. The first thing I noticed though was that the current top mu's are much more even than yesterday.

In other words, yesterday there was about a 4 point spread between rank 1 to 3 and also 3 to 30. At the moment there is a 3.2 spread from 1 to 3 and a 3.5 spread from 3 to 8. So only 2 ranks from where it would land with a completely uniform spread. Using the cdf approximation above actually places rank 1 between 4 and 5, closer to rank 3 than it should by 1 place.

I'm wondering if yesterday there just happened to be a number of the high ranked bots freshly submitted and climbing their way back up.

**Comment by bovard** [comment]
@DanielVF PlanetWars FTW!

**Comment by bovard** [comment]
@Janzert updated as per your comment, thanks!

**Comment by DanielVF** [comment]
Are there the right number of parenthesis in there?

**Comment by Janzert** [comment]
Oops sorry, yes it looks like I added an extra ) after the last mt_getrandmax call.

**Comment by erdman** [comment]
Noob Q:  Now that changes have been committed, when do they go live on the site?  Somebody please mark the time in a comment here so we can see the before-and-after behavior, thanks!

**Comment by truell20** [comment]
They go live on the site as soon as I pull them on our web server. I'll be sure to comment here when that happens.

**Comment by truell20** [comment]
Change is live.

**Comment by Janzert** [comment]
Now that the change has been in place for a bit here are the results from another spot check on game numbers. I sampled the 12 hours from midnight till noon today:

Rank | Name | Total | 12 hours
-----|-------|-------|------
1 | djma | 1914 | 25
2 | erdman | 297 | 30
3 | david-wu | 115 | 39
4 | Gullesnuffs | 124 | 36
5 | markstev | 331 | 41
6 | Daniel-Wang | 241 | 35
7 | Maximophone | 261 | 37
8 | nmalaguti | 234 | 48
9 | HalfVoxel | 288 | 47
10 | veden | 676 | 51
 | | | 
370 | xntrk | 958 | 32
371 | railgan | 1211 | 38
372 | danielborowski | 333 | 38
373 | trevormcdonald | 1276 | 35
374 | cdemet08 | 482 | 45
375 | JZebra | 150 | 54
376 | dvanbrug | 1121 | 36
377 | alastairbarnett | 325 | 36
378 | redwanrant | 103 | 45
379 | AkshayGoelTech | 1081 | 43
380 | tylerpreeve | 190 | 51

Top10: Average 38.9 Stdev 8.2 Middle: Average 41.2 Stdev 7 Overall: Average 40.1 Stdev 7.5

So djma is borderline on the number games he received being significantly lower. I personally don't think it's enough that it warrants a change at the moment though.

**Pull request merged**
