### PR TITLE
Julia [Final Steps]

### PR DESCRIPTION
**Pull request by truell20**

### CODE REVIEW

**Comment by truell20** [comment]
@xukai92 I'm getting 

```
ERROR: type cannot be constructed
 in include at boot.jl:238
at networking.jl:1
```
I installed Julia over apt

**Comment by xukai92** [comment]
@truell20 do you know which Julia version did you get from apt?

**Comment by truell20** [comment]
That issue was resolved once 0.5.0 was downloaded.

**Comment by truell20** [comment]
Am getting this error when running julia on our game servers:
```
ERROR: LoadError: LoadError: syntax: misplaced "local" declaration
while loading /home/ubuntu/Halite/worker/workingPath/1001/networking.jl, in expression starting on line 3
while loading /home/ubuntu/Halite/worker/workingPath/1001/MyBot.jl, in expression starting on line 2
```

**Comment by xukai92** [comment]
I tried freshly-installed Julia 0.5 on my Ubuntu machine - which looks all fine. Can you give your environment information and let me try to reproduce this error?

**Comment by truell20** [comment]
I am running it in a docker container on top of ubuntu.

**Comment by xukai92** [comment]
Is there anyway I can use that docker? Or can you please try changing

```julia
local _width
local _height
```

in `networking.jl` to

```julia
_width = nothing
_height = nothing
```

see if this can fix the issue.

**Comment by truell20** [comment]
Applied the fix you proposed, now I get:

``` --- Init ---
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:13
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:13
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:21
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:33
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:65
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/ubuntu/Halite/worker/workingPath/1001/networking.jl:85
```

**Comment by truell20** [comment]
[Here](https://github.com/HaliteChallenge/Halite/blob/master/worker/Dockerfile) is the Dockerfile.

**Comment by hgeorgako** [comment]
Any idea on when the starter kit for Julia will be available on the website for download? 
Thank you.

**Comment by xukai92** [comment]
@hgeorgako I'll try to get it done this week.

**Comment by xukai92** [comment]
@truell20 I've tried your Dockerfile and everything is fine to me. Here is how I installed the environment and did the test.

```bash
wget https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz
tar xzf julia-0.5.0-linux-x86_64.tar.gz
ln -s /root/julia/bin/julia /bin/julia
sh -c "$(curl -fsSL https://raw.githubusercontent.com/HaliteChallenge/Halite/master/environment/install.sh)"
ln -s /root/halite /bin/halite
git clone https://github.com/xukai92/Halite-Julia.git
cd Halite-Julia
./runGame.sh
```

**Comment by truell20** [comment]
We're using apt to install it. I'll switch it to your install method.

**Comment by xukai92** [comment]
How's it going?

**Pull request merged**
