### PR TITLE
Use a color blind safe palette in the visualizer.

### PR DESCRIPTION
**Pull request by Janzert**
Palette taken from post in http://forums.halite.io/t/visualizer-is-not-color-blind-friendly/751/3 which comes from http://mkweb.bcgsc.ca/biovis2012/

### CODE REVIEW

**Comment by Janzert** [comment]
Oops, this accidentally includes the changes from #349 as well.

**Comment by truell20** [comment]
The color palette is a little dull, so we might want to make it a toggle-able option.

**Comment by truell20** [comment]
Actually still not fully happy with it. The blues look quite similar. Graham also brought up some concerns.

**Comment by truell20** [comment]
Reverted the merge on master

**Pull request merged**
