### PR TITLE
Haskell Alternative

### PR DESCRIPTION
**Pull request by Josef-Vonasek**
A bit different approach for Haskell Starter Package. I have started working on it, before I found out there is already one implementation present, therefore my approach is little bit different (leading to different library structure). 

(Note: I am working with `git` for the first time, so it is very possible I have done something wrong. This should be a pull request to merge branches `haskell-v2 `and `haskell`).

### CODE REVIEW

**Comment by jparoz** [comment]
Hi Josef, I'm Jesse, I wrote the existing Haskell implementation.

Could you explain the rationale behind some of the design choices in this implementation? Particularly the use of a Reader monad for random number generation, and the existence of the App type. I don't see that it simplifies the code enough to be worthwhile: the random function is only called in one place in the implmentation I presented.

Many of the functions in this PR are incorrectly implemented, as far as I can tell. Additionally, MyBot.hs contains `undefined` where RandomBot.hs has a full implementation. This, like many of the other issues, is an easy fix; but as far as I can tell, this PR provides no value above the existing, accepted pull request. I would love to be proven wrong, however. 👍

**Comment by Josef-Vonasek** [comment]
Hi Jesse,

Firstly I would like to point out, that this implementation is not meant to replace yours, but maybe replace some parts of it (for example I find your `Network.hs` more appealing). I am also aware that not all of my implementations are not correct or even missing. But as you said, it is easy to fix them. The reason I have posted here unfinished work is to discuss with you the design choices I have made and finally if some of them are  valuable enough then also merge them into your project.

Now the most important part:

1. I have split the `communication implementation part` and `logic implementation part` into two files : `Main.hs` and `...Bot.hs`. If everything goes well, new competitor will not to be exposed to communication with server at all. 

2. Because of this, type signature of function `algorithm` should not change. Now this would be fine if the user would be doing only some transformation on input, but what if he also needs some part of `IO` for his work - like reading random numbers (Now it is very possible that random numbers are enough and you should never ever need anything more. In that case you don't need to read the rest of this paragraph). That means it should be possible to do any kind of `IO` action in algorithm, but at the same time, it should be as much pure as possible. My solution to this problem is to hide every IO action behind type class interface. Maybe there is a nicer solution to this problem. In that case I will be happy if you can share it with me :) . ( A nice side effect of this is that you can safely test your algorithm implementation trough `Test` type - for example by providing fake random numbers )

3. I think we should also consider using `(Vector (Vector Site))` Instead of `[[Site]]` for performance reasons.

4. The rest are just nit picks.

**Comment by jparoz** [comment]
Josef,

Thanks for the detailed and enlightening response! I think I have a much better handle on the ideas in this PR now. In response to each of your items:

1. I didn't really understand this before you pointed out the reasoning to me. I appreciate the idea, and it does seem very Haskell-ish. 😝 You're right in saying that the communications are completely identical for every bot, a fact I hadn't realised.  
I think I'd prefer, instead of having a pre-bottled `Main.hs`, simply exporting a `defaultMain` style library function, with a signature along the lines of: `defaultMain :: (signature of algorithm) -> String -> IO ()` . This would be used like this:
```haskell
main = defaultMain algorithm name
algorithm = ...
```
A potential counterpoint: It seems to me that there may come a point where we're starting to reach into code that contestants ought to write themselves. We are to provide an API layer, not a complete convenience library. I'm very open to further discussion.

2. This point seems slightly dubious to me. If the user should be allowed any kind of `IO` action, why should the type of the function be anything other than `IO`? The benefits of `Test` and similar tools are lessened then, but to retain those benefits, we could parametrise the monad type, e.g. `algorithm :: MonadIO m => Int -> GameMap -> m [Move]` or something like that.  
The current method of trapping the user into *just* random number generation, or as a matter of fact, into *just* any particular effect, seems like an arbitrary judgement on what kind of effect a bot should require to run.

3. `Vector (Vector Site)` is an obvious place to start optimising. It seemed premature, though, considering the one second per frame time limit, and the fact that we're competing with languages like Python. Adding the ubiquity of lists in Haskell, I just decided that if someone needs the extra performance, they can modify the code themselves. 😝

**Comment by Josef-Vonasek** [comment]
Jesse,

1. I am glad you like. I also find your idea of exporting main function very promising and convenient.

2. The thing with `IO` is it allows you to do anything you want. On the other hand if you **must** specify each impure action your code can do, you can reason about your algorithm much better. On top of that, adding new effects is really easy. Lets say you want to communicate with your external database - you just need to change the type signature: `algorithm :: (MyDatabeIO m, RandomReader m) => ID -> Map -> m [Moves]`.

3. You might be right. Although O(N) vs O(1) seems big on the paper, it might not be a big deal in a real scenario - especially with all Haskell optimizations. I would probably need to do some profiling before giving solid answer.

**Comment by jparoz** [comment]
On the second point, I'm still not sure I agree that it's completely worthwhile, but I can see that it's not as restrictive as I originally thought. Thinking more about it, if we provide `defaultMain`, then that can use `App` in the type signature for `algorithm`, but if one doesn't want to use `App`, they can simply forgo `defaultMain`. I'm quite pleased with this solution.

If we move forward in this way, how shall we proceed? I would suggest we rebase the changes in this PR to use more of the existing code, then reopen the pull request.

**Comment by Josef-Vonasek** [comment]
That sounds reasonable. 

Forgive me my inexperience. I tried `git rebase haskell` but it says `Current branch haskell-v2 is up to date.` What am I doing wrong?

**Comment by Josef-Vonasek** [comment]
My little to zero git experience turned out to be a big problem, so I have rather started from scratch to make sure nothing goes wrong.

**Pull request closed without merging**
