### PR TITLE
Reorganize Halite Documentation

### PR DESCRIPTION
**Pull request by nmalaguti**
Reorganize how Halite is documented and switch from using HTML to using
Markdown.

### CODE REVIEW

**Comment by nmalaguti** [comment]
This isn't ready yet, only a few pages have been converted, but I wanted to get some feedback on the approach.

**Comment by truell20** [comment]
Why make a different .php file for every page of the reference? Why not just use a .htaccess file and one .php file for all of the reference pages. We could just check the filename of the url and then load the appropriate md file inside of the HTML/CSS boilerplate.

**Comment by truell20** [comment]
This is like what we do with our API endpoints. See:

https://github.com/HaliteChallenge/Halite/blob/master/website/api/web/.htaccess
https://github.com/HaliteChallenge/Halite/blob/master/website/api/web/api.php

**Comment by nmalaguti** [comment]
Sure, that sounds great. I'll figure out how to make that work.

**Comment by truell20** [comment]
Might want to switch to a sidebar menu like [bootstrap's](http://getbootstrap.com/css/) (scrolls as you scroll, active menu item changes as you scroll), since the pages are so long.

The alternative would be breaking up the long pages.

**Comment by truell20** [comment]
Also we will probably want to switch to styling that better differentiates the headers.

**Comment by truell20** [comment]
@Sydriax and I will make passes through the docs this weekend. I'll add in the .htaccess php trick. We hope to merge by Monday.

**Comment by truell20** [comment]
Are any of the existing pages not converted?

**Comment by truell20** [comment]
Moved to this PR https://github.com/HaliteChallenge/Halite/pull/321. @nmalaguti to make changes, just PR into that branch.

**Pull request closed without merging**
