### PR TITLE
Go Starter Package [Final Steps]

### PR DESCRIPTION
**Pull request by truell20**
Checklist
* ~~Make sure all proper files are present (MyBot, RandomBot, runGame.sh, runGame.bat)~~
  * Need runGame.bat
* ~~Add dependencies to docker file~~
* Test on game servers
* Add to archive script
* Add to downloads
* Update game server reference

### CODE REVIEW

**Comment by Janzert** [comment]
Is this waiting on anything or just time from the organizers?

**Comment by truell20** [comment]
@Janzert Was just waiting on us

**Comment by l2dy** [comment]
@truell20 Go uses Tabs for indentation.

**Comment by truell20** [comment]
Thanks so much @l2dy. Those changes are now live on the site and pushed to master.

**Pull request merged**
