### PR TITLE
Julia Starter Package

### PR DESCRIPTION
**Pull request by xukai92**
For Julia 0.5 (latest) only

### CODE REVIEW

**Comment by truell20** [comment]
Why close this?

**Comment by xukai92** [comment]
Sorry there seems a bug in my translation. I'm working on to fix it.

**Comment by xukai92** [comment]
Hi all. I fixed the bug, which is some messy caused by the fact that index of Julia starts from 1 but Python from 0 (I translated that from Python version).

**Comment by xukai92** [comment]
Why my next commits not showing up?

**Comment by xukai92** [comment]
Hi @truell20 , will the sever support Julia in near future?

**Comment by truell20** [comment]
Yes. After reviewing this PR, we will merge it into a non-master branch, add Julia to the server, etc

**Comment by xukai92** [comment]
So does the sever support Julia now?

**Comment by truell20** [comment]
Not yet. Will by the end of today.

**Comment by xukai92** [comment]
Cool. Thanks for your work!

**Comment by truell20** [comment]
No problem. Thanks for contributing!

**Pull request merged**
