### PR TITLE
Add Go pack

### PR DESCRIPTION
**Pull request by georgyo**

### CODE REVIEW

**Comment by truell20** [comment]
How should we build this?

**Comment by georgyo** [comment]
What do you mean? In addition to [runGame.sh](https://github.com/georgyo/Halite/blob/ecffaa00449e8d2ce54ac0a9454432ec326ad3ca/airesources/Go/runGame.sh)? Just having go installed, and runGame.sh should be plenty sufficient.


Related: After I submitted this, I wanted to test building using the worker, however, I can't seem to figure out how that works. I can't even figure out how you are calling the worker. You never load the build code you have there into the container.

There are a few scripts in the worker directory, but a really useful one would be the ability to pass a zip file  location and have the worker container build it, exactly as it would on the server. This would let me people test their bot.zips before they send them to the server.

**Comment by truell20** [comment]
Nevermind. I was having some problems with the run game script, but they had to do with my Go installation.

**Comment by truell20** [comment]
We have many worker servers. They run `worker.py` continuously and query a manager server for tasks. After the running of `install.sh`, workers are started by running `worker.py` in a screen session (using `startWorkerScreen.sh`).

> You never load the build code you have there into the container.

What do you mean by build code?

> There are a few scripts in the worker directory, but a really useful one would be the ability to pass a zip file location and have the worker container build it, exactly as it would on the server. This would let me people test their bot.zips before they send them to the server.

Totally agree. I'll open up a second ticket.

**Comment by truell20** [comment]
We can take it from here.

**Pull request merged**
