### PR TITLE
Adding replay controls for directory and no replay

### PR DESCRIPTION
**Pull request by veden**

### CODE REVIEW

**Comment by truell20** [comment]
Getting this error

```
core/Halite.cpp: In member function ‘GameStatistics Halite::runGame(std::vector<std::basic_string<char> >*, unsigned int, unsigned int, bool, std::string)’:
core/Halite.cpp:388:9: error: ‘enabledReplay’ was not declared in this scope
     if (enabledReplay) {
```

**Comment by veden** [comment]
that last commit should have been a fix for that

**Comment by veden** [comment]
when I undid the spacing, I reverted that change and forgot to add it back in.

**Comment by veden** [comment]
this doesn't redirect the error reports, I don't know if that is desired as well.

**Pull request merged**
