### PR TITLE
Pull conn.sendName(...) logic out of NewConnection()

### PR DESCRIPTION
**Pull request by jerold**
Timeout for 1st round is 15 seconds. This change allows bots written in
go to take advantage of that extra time.

### CODE REVIEW

**Comment by jerold** [comment]
@Sydriax @truell20 Ready for your review.

**Comment by jerold** [comment]
This changes the public facing api for the go developer package. As it takes the name param out of the NewConnection method.

**Comment by truell20** [comment]
lgtm

**Comment by Janzert** [comment]
One other thing to note if you're looking to take advantage of the 15 second startup time with a Go bot. Currently Go bots do not get compiled ahead of time but instead are compiled during the startup time at the beginning of each game with a `go run MyBot.go` command.

So you might want to look at getting the correct commands into `compiler.py` to compile the bot ahead of time.

**Comment by truell20** [comment]
^ This is true.

**Comment by truell20** [comment]
Relevant code section is here: https://github.com/HaliteChallenge/Halite/blob/master/worker/compiler.py#L334

**Comment by jerold** [comment]
Thanks guys!

**Pull request merged**
