### PR TITLE
Adding association window and capabilities

### PR DESCRIPTION
**Pull request by j-clap**
Modifications necessary to associate with an institution of any level. NOTE: Databases must be populated prior to function (i.e.: HighSchool and Scrimmage must be created and populated and User must be updated).

### CODE REVIEW

**Comment by truell20** [comment]
What exactly is the function of a scrimmage? Correct me if I'm wrong, but they don't seem to be integrated into the UI (other than the selection of a scrimmage on `associate.php`).

**Comment by truell20** [comment]
A couple more questions:
* How will scrimmages be added to the UI? Will there be something like a leaderboard for each scrimmage?
* Shouldn't we wait until scrimmages are in the UI before merging and unveiling? Or, should we merge, but take scrimmages out as an option on `associate.php` until they are added to the UI?
* What do you mean by "another which begins to New York and Massachusetts"?

Thank you again for all of the work you've done!

**Comment by j-clap** [comment]
* They will be RESTful endpoints which will present specific leaderboards (like SELECT * FROM User WHERE Scrimmage='New York Competition 2016' ORDER BY Score), so that is correct :)
* I think it's okay to have it as part of the association (i.e.: the POST) but not the leaderboard (i.e.: the GET), since it's important to have users present in the scrimmage before displaying it. We should populate the table with the scrimmage names before allowing the associate, though. But ultimately it's up to you; I trust your decision.
* Sorry, my phone autocorrected and I didn't realize. To expound: there could be scrimmages (or competitions) between states, like, there could be a scrimmage which would pit New York high schools vs Massachusetts high schools. This is possible by populating the scrimmage table with a scrimmage A which has two rows, one {A, MA}, and another {A, NY}. That way we can have inter-state competitions.

And of course, happy to help :)

**Comment by truell20** [comment]
Thanks for the quick reply. More questions!

* How will users navigate to the scrimmage leaderboards? 
  * Will there be a new tab on the navbar for scrimmages and brings you to a page of scrimmage listings?
  * Will it be integrated into `user.php`? Maybe just like we currently have a link to your place on the global leaderboard, we could also include a link to your place on your scrimmages leaderboard.
  * These suggested changes make me worried about cluttering the UI.
* I might be wrong, but my intuition is that it would be less confusing for users if we have the UI up on the unveiling of this feature.
* Giving users a choice between a number of scrimmages is interesting, but I don't see how new users are supposed to choose between scrimmages. Why would they care whether they are in a NY scrimmage or a Massachusetts/NY challenge? Might it be better to essentially collapse the scrimmage concept into statewide, high school leaderboards?

**Comment by truell20** [comment]
@Sydriax suggested that scrimmages are accessible through subdomains with this schema: `scrimmage_name.halite.io`. I quite like that idea since scrimmages are only really relevant to scrimmage owners and it doesn't clutter the UI.

**Comment by j-clap** [comment]
Apologies for the delay in reply (been a busy couple of days). Answers as follows:
* The idea would be to have a RESTful leaderboards set of pages (that is to say, something like halite.io/leaderboard/level/high_school/scrimmage/ny_2017). Participating scrimmages could be viewable through the top level pages; i.e.:
    1. Top-most page:
        * User goes to main Halite page
        * User clicks Leaderboards/Ranking (uri: halite.io/leaderboard)
        * User selects level
        * User scrimmage choices for that level are shown and filtered by state and schools
    2. User page:
        * A type of user profile page gives the user the choice to see his scores in previous leaderboards and to see his current performance, with a link to the leaderboards page.
* We could work on the first option for now to show a simple leaderboard accessible when clicking Rankings, to filter by a drop-down of High School or Professional. I believe we're expecting only one scrimmage for the first competition, so we can (for now) just use it as the title of the ranking page once filtered as high school rankings.
* Just to note, scrimmage is a special concept, which would be advertised in the high schools themselves, and that's how the students would know to join. So they would really just be specially advertised high school competitions.
* I recall that Mark, Alfred and I did discuss the subdomain schema, but we ultimately agreed that RESTful would be better as it would allow better modularity and maintain a paging subdivision (i.e.: every page in the REST URI would be accessible:  halite.io/leaderboard, halite.io/leaderboard/level, halite.io/leaderboard/level/high_school, halite.io/leaderboard/level/high_school/scrimmage, halite.io/leaderboard/level/high_school/scrimmage/ny_2017. To do this same method with the subdomain schema might look strange. But up to you :)

**Comment by truell20** [comment]
Great! In the interest of time, before merging, I believe that this is what is left:
* Take scrimmage selection out of the UI (`associate.php`)
* Add in leaderboard dropdown filter based on level (Professional, High School, etc)
* Require reporting of level on first sign up (like we do with email)

Sound good? 

I can knock out the above points pretty quickly, make the database mods, merge, and then push to production.

**Comment by j-clap** [comment]
Yessir :) Sounds like a plan.

On Jan 3, 2017 8:35 PM, "Michael Truell" <notifications@github.com> wrote:

Great! In the interest of time, before merging, I believe that this is what
is left:

   - Take scrimmage selection out of the UI (associate.php)
   - Add in leaderboard dropdown filter based on level (Professional, High
   School, etc)
   - Require reporting of level on first sign up (like we do with email)

Sound good?

I can knock out the above points pretty quickly, make the database mods,
merge, and then push to production.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HaliteChallenge/Halite/pull/359#issuecomment-270274272>,
or mute the thread

**Comment by truell20** [comment]
All that's left is:

* Add in leaderboard dropdown filter based on level (Professional, High School, etc)

I'll push that bit by the end of today, Saturday Jan 7.

**Pull request merged**
