### PR TITLE
Initial commit of Python starter package rewrite.

### PR DESCRIPTION
**Pull request by erdman**
I just dropped in everything verbatim from my alt-starter-package.

### CODE REVIEW

**Comment by erdman** [comment]
I'm not sure which of the changes is the most important driver of the speedups.  To demonstrate the speed improvements, I've attached two timing logs of the ImprovedBot.py (aka NorthWestBot.py), one based on the tutorial on website, and the other as translated for the alt-starter.  I then ran:
`./halite -q -d "50 50" -s 123456789 "python3 ImprovedBot.py"`
The logs show milliseconds used per turn, and suggests 4x speedup on this starter bot logic.  I think users will see even greater speedup multiples with more complicated logic.
[OfficialPkg-ImprovedBot.log.txt](https://github.com/HaliteChallenge/Halite/files/643590/OfficialPkg-ImprovedBot.log.txt)
[AltPkg-ImprovedBot.log.txt](https://github.com/HaliteChallenge/Halite/files/643592/AltPkg-ImprovedBot.log.txt)

**Comment by truell20** [comment]
Could you remove all non-random bots (AmbiturnerBot.py, ImprovedBot.py, etc)

**Comment by truell20** [comment]
@Sydriax will rewrite the improving the random bot sections to use this starter package. I'll look into travis. Then we should be good to merge.

**Comment by truell20** [comment]
Oh and also we need to edit the README.

**Comment by erdman** [comment]
@Sydriax, I rewrote the gist's from the "Improving the RandomBot" section, if you'd like to use them:
https://gist.github.com/erdman

I'll revise the README.

**Comment by erdman** [comment]
@Sydriax, know you guys are busy, so I took a first cut at updating the "How to Improve the RandomBot" php web page for you.  Please revise as you see fit.

**Comment by truell20** [comment]
Thanks so much for that!

**Comment by truell20** [comment]
There's an error in Revision4.py. Use use `location` when you mean `square`.

**Comment by truell20** [comment]
Have fixed tests locally so should be good to merge after that.

**Comment by erdman** [comment]
> There's an error in Revision4.py. Use use location when you mean square.

Fixed.

**Pull request merged**
