### PR TITLE
Add actual map size reporting.

### PR DESCRIPTION
**Pull request by Janzert**
Fixes issue #200

### CODE REVIEW

**Comment by truell20** [comment]
Why use "Final map size" in quiet mode. Also, the environment command line page needs to be updated.

**Comment by Janzert** [comment]
> Why use "Final map size" in quiet mode

Mostly it's no harder for the script to parse, easier for the human and doesn't add a conditional in the code.

Ah, didn't see the quiet mode description in the command line page. It's already wrong in a few different ways, but I'll give a pass at fixing it.

**Comment by erdman** [comment]
If users specify the seed and the actual map size (as reported here) in a new game, will they get the same map as when specifying the same seed and the original/requested map size?  Remember, halite environment can now choose a map size when not specified, so users might not even know what was requested.  Replay-ability is important.  If putting actual map size results in a different map, we probably also want to report the requested map size.  It's an oversight on my part that we haven't already been reporting requested map size.

**Comment by Janzert** [comment]
From my reading of the code (and one test ;) ) the same map is guaranteed to result from using the actual map size or the initially requested map size (or any size in between).

**Comment by truell20** [comment]
I took out `Final map size:` for the time being for the sake of consistency.

**Pull request merged**
